### ISSUE TITLE
Code injection

### ISSUE THREAD

**Issue by nz2Dev** [farukcankaya/ciappsigningexample#1]
What if a developer injects code in the CI pipeline that would read Environment variables and just show them in a console or send them somewhere else so that it will be compromised after.
Is there any restriction for that cases?

**Comment by farukcankaya** [comment]
Sorry for the late response @nz2Dev! Actually, you should not work with a developer that you don't trust :D . If there is a trust problem, you can build a custom pipeline with [Jenkins Pipeline](https://jenkins.io/doc/book/pipeline/) and you can separate build process from the codebase totally.

If you make an open source project, setting up Jenkins pipeline is not the case for most cases. Hosted CI solutions such as TravisCI and Circle CI can be used in that case as I did in this project. These hosted CI's have some restriction to secure environment variables. For example, environment variables cannot be shown in console with simple commands like 'echo'. You can check the document for more information:
- Travis CI Best practices: https://docs.travis-ci.com/user/best-practices-security/
- Circle CI Best practices: https://discuss.circleci.com/t/huge-security-issue-with-environment-variables/23175/2

Of course, these restrictions cannot secure credentials totally. A Developer can insert a code that isn't detected from hosted CI's and credentials can be leaked. I think the best solution should be like that:
- Builts should be from predetermined branches. For example, only "**development**" branch can be built from CI.
- Close pushing **development** branch directly.
- Change rule settings to "require pull request reviews before merging" and "require approved reviewers at least 1".

In that way, you can review codes that sent by all developers and you'll not accept code that causes the leak.

**Comment by nz2Dev** [comment]
Thank you for the response @farukcankaya! The idea with close pushing branch is what I was searching for :)
